name: delivery_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.4
  audioplayers: ^6.5.1
  vibration: ^3.1.5
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.0.1
  geolocator: ^13.0.2
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/constants/dummy_data.json
    - assets/sounds/
    - assets/images/
