// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv6rsi89Fbayk6CQ3qXIvyFyKkASYIn_U',
    appId: '1:247303180375:web:e1e3ceae24e0dd65dad312',
    messagingSenderId: '247303180375',
    projectId: 'api-expedition-app',
    authDomain: 'api-expedition-app.firebaseapp.com',
    storageBucket: 'api-expedition-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyLWDybSEqyfS-FgLjiBQ6vaLr0geqP4o',
    appId: '1:247303180375:android:d48a3d8e507a8bb0dad312',
    messagingSenderId: '247303180375',
    projectId: 'api-expedition-app',
    storageBucket: 'api-expedition-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaLat0HPiPj5VGnkLif_tkMRnZvHXmjtY',
    appId: '1:247303180375:ios:989a69e46671fc88dad312',
    messagingSenderId: '247303180375',
    projectId: 'api-expedition-app',
    storageBucket: 'api-expedition-app.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaLat0HPiPj5VGnkLif_tkMRnZvHXmjtY',
    appId: '1:247303180375:ios:989a69e46671fc88dad312',
    messagingSenderId: '247303180375',
    projectId: 'api-expedition-app',
    storageBucket: 'api-expedition-app.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv6rsi89Fbayk6CQ3qXIvyFyKkASYIn_U',
    appId: '1:247303180375:web:b8acf1ad22ab3f94dad312',
    messagingSenderId: '247303180375',
    projectId: 'api-expedition-app',
    authDomain: 'api-expedition-app.firebaseapp.com',
    storageBucket: 'api-expedition-app.firebasestorage.app',
  );
}
